### ISSUE TITLE
cwd of tmux session is not used for action invocation

### ISSUE THREAD

**Issue by iloveitaly** [abhinav/tmux-fastcopy#148]
This causes issues if you have a regex which matches against a relative path and an action which grabs the full path using the pwd.

ex: https://github.com/iloveitaly/dotfiles/blob/master/.open-file-path.sh

Would be great if the cwd in the action runner matched the tmux cwd.

**Comment by abhinav** [comment]
This makes sense and was straightforward to implement. Expect a PR soon-ish.
Thanks for the suggestion!
