### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by m040601** [abhinav/tmux-fastcopy#38]
First of all thank you for your work in this clever tool.

I've been following it and testing it, since the first releases.
I've been comparing it and testing it with others that provide  similar "hinting" to copy to the tmux buffer.

Everything works fine.

Except, when there's nothing to find or no regex to match (CASE1).

That is, for ex. , if i open a  new tmux window, with a fresh empty buffer, with nothing being displayed except my prompt.

When i fire tmux-fastcopy, it simply greys out everything, and the CPU usage shoots up.

I have to abort it with C-c. Nothing gets copied to the buffer.

If I have a little more to be found (CASE2) then it works as usual.
https://imgur.com/a/zNUKall

I have to say that I use the released compiled version, on ArchLinux.
I simply have this on my .tmux.conf,

bind-key F run-shell -b ~/.tmux.d/experiments/tmux-fastcopy

**Comment by abhinav** [comment]
Fix released. Thanks again @m040601.

**Comment by m040601** [comment]
Nice. I'm not even a programmer, so I wasnt even sure this was some coding problem.
I've also tested 0.5 and everything works ok now.

**Comment by abhinav** [comment]
Ah, I thought the high cpu was related to the match. I'll dig into that separately. I suspect it's the render loop which runs at 60 fps right now, which may not be necessary.

**Comment by abhinav** [comment]
Never mind, it wasn't the render loop. I found the root cause; it had to do with logging. Fix incoming.

**Comment by abhinav** [comment]
This should be fixed in v0.5.1.

Before:
![image](https://user-images.githubusercontent.com/41730/132615471-97ba5557-578e-4284-b0b6-bdaa471440a8.png)

After:
![image](https://user-images.githubusercontent.com/41730/132615525-e108de5d-fb5c-439e-97ce-3020aee60fa0.png)

Thanks again @m040601.

**Comment by m040601** [comment]
> This should be fixed in v0.5.1.

Yeap.  Tested and confirmed on my system too. Great job !
