### ISSUE TITLE
Confusion around regex matching

### ISSUE THREAD

**Issue by arcaartem** [abhinav/tmux-fastcopy#48]
Hi Abhinav,

Thanks very much for writing this plugin, it's very handy! 

I have a question regarding custom regex matching. I have the following line in my `.tmux.config` file and I'm expecting it to match the text `"hello"` on a pane (double-quotes included), but it doesn't. Instead, it matches `'"hello"'`:

`set-option -g @fastcopy-regex-test1 "\"hello\""`

I've also tried the following but the end result is the same; it matches `'"hello"'`:

`set-option -g @fastcopy-regex-test4 '"hello"'`

I'm reaching out to you in case it's something you may know already and can point me in the right direction.

Thanks,
Arca

**Comment by abhinav** [comment]
Hello, @arcaartem! I'm happy to hear that you found the plugin useful.
Thanks for the report; I've reproduced it locally. This is indeed a bug.
Expect a fix shortly.

Thanks!

**Comment by abhinav** [comment]
Fix released in 0.6.2!
Please try now, @arcaartem.
Thanks!

**Comment by arcaartem** [comment]
Amazing, thanks @abhinav !
